//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danisman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public danisman()
        {
            this.ajandas = new HashSet<ajanda>();
            this.danisman1 = new HashSet<danisman>();
            this.filtres = new HashSet<filtre>();
            this.portfoys = new HashSet<portfoy>();
            this.services = new HashSet<service>();
            this.histories = new HashSet<history>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Ozgecmis { get; set; }
        public string Bolge { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Onay { get; set; }
        public string PhotoPath { get; set; }
        public string Gorevi { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Sicil { get; set; }
        public string Kimlik { get; set; }
        public string Yeterlilik { get; set; }
        public string DanismanSozlesme { get; set; }
        public Nullable<bool> Kabul { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Broker { get; set; }
        public Nullable<bool> Mudur { get; set; }
        public Nullable<bool> Asistan { get; set; }
        public Nullable<bool> DanismanMi { get; set; }
        public Nullable<bool> Tasarim { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public string CompanyName { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiPhone { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string OfficeContact { get; set; }
        public string UparazziName { get; set; }
        public string BrokerLogo { get; set; }
        public Nullable<int> EkipOrder { get; set; }
        public Nullable<bool> Showroom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ajanda> ajandas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danisman> danisman1 { get; set; }
        public virtual danisman danisman2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<filtre> filtres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<portfoy> portfoys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> histories { get; set; }
    }
}
