//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class filtre
    {
        public int Id { get; set; }
        public Nullable<int> DanismanId { get; set; }
        public Nullable<decimal> UnitPriceMin { get; set; }
        public Nullable<decimal> UnitPriceMax { get; set; }
        public Nullable<int> m2Min { get; set; }
        public Nullable<int> m2Max { get; set; }
        public string Nitelik { get; set; }
        public Nullable<int> IlId { get; set; }
        public Nullable<int> IlceId { get; set; }
        public Nullable<int> MahId { get; set; }
        public Nullable<bool> Satilik { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Title { get; set; }
    
        public virtual city city { get; set; }
        public virtual danisman danisman { get; set; }
    }
}
