//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int Id { get; set; }
        public Nullable<int> DanismanId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Action { get; set; }
        public Nullable<bool> forAdmin { get; set; }
    
        public virtual danisman danisman { get; set; }
    }
}
