//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class islem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string RaporNo { get; set; }
        public Nullable<bool> Satilik { get; set; }
        public string PortfoyNo { get; set; }
        public string Nitelik { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Belde { get; set; }
        public string AdaNo { get; set; }
        public string Parsel { get; set; }
        public string m2 { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public string Kat { get; set; }
        public Nullable<int> No { get; set; }
        public string OdaSayisi { get; set; }
        public string RoutingS { get; set; }
        public string AdS { get; set; }
        public string AdresS { get; set; }
        public string TCS { get; set; }
        public string TelS { get; set; }
        public string DanismanS { get; set; }
        public string Danisman2S { get; set; }
        public Nullable<decimal> BrütS { get; set; }
        public Nullable<System.DateTime> TapuTarihiS { get; set; }
        public string TahsilatS { get; set; }
        public Nullable<decimal> ToplamRapor { get; set; }
        public string RoutingA { get; set; }
        public string AdA { get; set; }
        public string AdresA { get; set; }
        public string TCA { get; set; }
        public string TelA { get; set; }
        public string DanismanA { get; set; }
        public string Danisman2A { get; set; }
        public Nullable<decimal> BrütA { get; set; }
        public Nullable<System.DateTime> TapuTarihiA { get; set; }
        public string TahsilatA { get; set; }
        public Nullable<int> PortfoyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> BrokerOnay { get; set; }
        public Nullable<bool> YonetimOnay { get; set; }
    
        public virtual portfoy portfoy { get; set; }
    }
}
