//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpArazziDBEntities : DbContext
    {
        public UpArazziDBEntities()
            : base("name=UpArazziDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ajanda> ajandas { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<danisman> danismen { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<errortable> errortables { get; set; }
        public virtual DbSet<filtre> filtres { get; set; }
        public virtual DbSet<fotograf> fotografs { get; set; }
        public virtual DbSet<haber> habers { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<islem> islems { get; set; }
        public virtual DbSet<kurumsal> kurumsals { get; set; }
        public virtual DbSet<mail> mails { get; set; }
        public virtual DbSet<mm> mms { get; set; }
        public virtual DbSet<neighborhood> neighborhoods { get; set; }
        public virtual DbSet<ozellik> ozelliks { get; set; }
        public virtual DbSet<portfoy> portfoys { get; set; }
        public virtual DbSet<portfoyozellik> portfoyozelliks { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<slider> sliders { get; set; }
        public virtual DbSet<sozluk> sozluks { get; set; }
        public virtual DbSet<town> towns { get; set; }
    }
}
