//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class portfoyozellik
    {
        public int Id { get; set; }
        public Nullable<int> PortfoyId { get; set; }
        public Nullable<int> OzellikId { get; set; }
    
        public virtual ozellik ozellik { get; set; }
        public virtual portfoy portfoy { get; set; }
    }
}
