//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpArazzi2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int Id { get; set; }
        public Nullable<int> DanismanId { get; set; }
        public Nullable<System.DateTime> MeetDate { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public string DosyaNo { get; set; }
        public Nullable<int> NeighborhoodId { get; set; }
        public string AdaParsel { get; set; }
        public Nullable<int> m2 { get; set; }
        public string Nitelik { get; set; }
        public string IletisimNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public string Note { get; set; }
        public string PortfoyDetay { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Gonderen { get; set; }
    
        public virtual danisman danisman { get; set; }
        public virtual neighborhood neighborhood { get; set; }
    }
}
